### ISSUE TITLE
".bump-version.el" is unintentionally distributed

### ISSUE THREAD

**Issue by zonuexe** [atykhonov/google-translate#154]
When installing a package from MELPA, a warning is issued because an unexpected file is distributed.

<img width="658" alt="スクリーンショット 2022-09-20 23 39 06" src="https://user-images.githubusercontent.com/822086/191295237-546db640-8217-4af4-b47b-1caf079273ea.png">

**Comment by stardiviner** [comment]
Hmm, I checked the git log of file `.bump-version.el`, have not found any related other source code file or make tools or CI etc requires this file. Don't know what's the original purpose (might just for mark package version). Also I searched MELPA packages list, have not found any "bump-version" likely names package tools. Also MELPA seems only check version from source code comments metadata. Should be fine to remove this file to remove old settings (because the latest commit is 3 years ago).
